apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: FunnyJokes
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: FunnyJokes
        tier: frontend
        track: stable
    spec:
      containers:
        - name: funny-jokes-frontend
          image: dbms_task-frontend
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: funny-jokes-frontend-service
spec:
  selector:
    app: FunnyJokes
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funny-jokes-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-funny-jokes.com
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: funny-jokes-frontend-service
            port:
              number: 3000